export interface CfdiData {
  version: string;
  folioFiscal: string;
  serie: string;
  folio: string;
  tipoDescarga: string;
  rfc: string;
  empleado: string;
  regimenFiscal: string;
  codigoPostal: string;
  numEmpleado: string;
  numSeguroSocial: string;
  banco: string;
  cuentaBancaria: string;
  regimenContratacion: string;
  fechaInicioRelLaboral: string;
  departamento: string;
  puesto: string;
  riesgo: string;
  tipoContrato: string;
  periodicidadPago: string;
  tipoJornada: string;
  sbc: string;
  sdi: string;
  tipoNomina: string;
  fechaInicialPago: string;
  fechaFinalPago:string;
  diasPagados: string;
  fechaPago: string;
  tipo: 'Percepción' | 'Deducción';
  claveSat: string;
  claveInterna: string;
  concepto: string;
  importeGravado: number;
  importeExento: number;
  fechaEmision: string;
  fechaTimbrado: string;
  estatus: string;
}
