name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # Cambia si tu rama de producción es diferente
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # Usa la versión que tu proyecto requiere

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DESERT_0F1F8311E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # raíz del proyecto
          api_location: ""           # si no tienes API
          output_location: ".next"   # ⚡ usa '.next' si solo haces `next build`
          # output_location: "out"   # ⚡ usa 'out' si haces `next export`
